insert into Autores (nome, nacionalidade) values ('Bianka', 'Egypt');
insert into Autores (nome, nacionalidade) values ('Ermanno', 'Russia');
insert into Autores (nome, nacionalidade) values ('Cynthy', 'Thailand');
insert into Autores (nome, nacionalidade) values ('Wally', 'Indonesia');
insert into Autores (nome, nacionalidade) values ('Merline', 'Portugal');
insert into Autores (nome, nacionalidade) values ('Jodie', 'Philippines');
insert into Autores (nome, nacionalidade) values ('Cherilyn', 'Faroe Islands');
insert into Autores (nome, nacionalidade) values ('Lucy', 'Indonesia');
insert into Autores (nome, nacionalidade) values ('Dewie', 'China');
insert into Autores (nome, nacionalidade) values ('Rodolph', 'China');
insert into Autores (nome, nacionalidade) values ('Dacia', 'Indonesia');
insert into Autores (nome, nacionalidade) values ('Gwyn', 'Mongolia');
insert into Autores (nome, nacionalidade) values ('Neale', 'Egypt');
insert into Autores (nome, nacionalidade) values ('Linnell', 'China');
insert into Autores (nome, nacionalidade) values ('Augustus', 'Ecuador');
insert into Autores (nome, nacionalidade) values ('Mendel', 'Philippines');
insert into Autores (nome, nacionalidade) values ('Burnard', 'Russia');
insert into Autores (nome, nacionalidade) values ('Kristin', 'Indonesia');
insert into Autores (nome, nacionalidade) values ('Dennet', 'United States');
insert into Autores (nome, nacionalidade) values ('Hallsy', 'China');
