insert into Autores (codAutor,nome, nacionalidade) values (1,'Bianka', 'Egypt');
insert into Autores (codAutor,nome, nacionalidade) values (2,'Ermanno', 'Russia');
insert into Autores (codAutor,nome, nacionalidade) values (3,'Cynthy', 'Thailand');
insert into Autores (codAutor,nome, nacionalidade) values (4,'Wally', 'Indonesia');
insert into Autores (codAutor,nome, nacionalidade) values (5,'Merline', 'Portugal');
insert into Autores (codAutor,nome, nacionalidade) values (6,'Jodie', 'Philippines');
insert into Autores (codAutor,nome, nacionalidade) values (7,'Cherilyn', 'Faroe Islands');
insert into Autores (codAutor,nome, nacionalidade) values (8,'Lucy', 'Indonesia');
insert into Autores (codAutor,nome, nacionalidade) values (9,'Dewie', 'China');
insert into Autores (codAutor,nome, nacionalidade) values (10,'Rodolph', 'China');
insert into Autores (codAutor,nome, nacionalidade) values (11,'Dacia', 'Indonesia');
insert into Autores (codAutor,nome, nacionalidade) values (12,'Gwyn', 'Mongolia');
insert into Autores (codAutor,nome, nacionalidade) values (13,'Neale', 'Egypt');
insert into Autores (codAutor,nome, nacionalidade) values (14,'Linnell', 'China');
insert into Autores (codAutor,nome, nacionalidade) values (15,'Augustus', 'Ecuador');
insert into Autores (codAutor,nome, nacionalidade) values (16,'Mendel', 'Philippines');
insert into Autores (codAutor,nome, nacionalidade) values (17,'Burnard', 'Russia');
insert into Autores (codAutor,nome, nacionalidade) values (18,'Kristin', 'Indonesia');
insert into Autores (codAutor,nome, nacionalidade) values (19,'Dennet', 'United States');
insert into Autores (codAutor,nome, nacionalidade) values (20,'Hallsy', 'China');