insert into Livros (codAutor, Titulo, Editora, Edicao, NumeroPagina) values (19, 'Palm Beach Story, The', 'Brainbox', 2, 29);
insert into Livros (codAutor, Titulo, Editora, Edicao, NumeroPagina) values (1, 'We and the I, The', 'Centidel', 5, 248);
insert into Livros (codAutor, Titulo, Editora, Edicao, NumeroPagina) values (4, 'Paleface, The', 'Skibox', 5, 181);
insert into Livros (codAutor, Titulo, Editora, Edicao, NumeroPagina) values (16, 'Just Anybody (Le premier venu)', 'Trupe', 3, 171);
insert into Livros (codAutor, Titulo, Editora, Edicao, NumeroPagina) values (17, 'Murder Over New York', 'Skaboo', 4, 352);
insert into Livros (codAutor, Titulo, Editora, Edicao, NumeroPagina) values (8, 'Decoy', 'Centizu', 4, 143);
insert into Livros (codAutor, Titulo, Editora, Edicao, NumeroPagina) values (12, 'What''s Love Got to Do with It?', 'Zoomzone', 3, 181);
insert into Livros (codAutor, Titulo, Editora, Edicao, NumeroPagina) values (14, 'Waking Up in Reno', 'Zoovu', 3, 95);
insert into Livros (codAutor, Titulo, Editora, Edicao, NumeroPagina) values (16, 'Waiting...', 'Viva', 3, 170);
insert into Livros (codAutor, Titulo, Editora, Edicao, NumeroPagina) values (3, 'Aladdin and the King of Thieves', 'Shuffledrive', 3, 319);
insert into Livros (codAutor, Titulo, Editora, Edicao, NumeroPagina) values (16, 'Queen of Versailles, The', 'Twitterbeat', 5, 181);
insert into Livros (codAutor, Titulo, Editora, Edicao, NumeroPagina) values (9, 'Lights in the Dusk (Laitakaupungin valot)', 'Kimia', 2, 384);
insert into Livros (codAutor, Titulo, Editora, Edicao, NumeroPagina) values (10, 'Scenic Route, The', 'Blogpad', 4, 168);
insert into Livros (codAutor, Titulo, Editora, Edicao, NumeroPagina) values (4, 'Mega Piranha', 'Dynazzy', 4, 360);
insert into Livros (codAutor, Titulo, Editora, Edicao, NumeroPagina) values (7, 'Devil''s Rock, The', 'Livetube', 1, 274);
insert into Livros (codAutor, Titulo, Editora, Edicao, NumeroPagina) values (20, 'Bringing Down the House', 'Linkbuzz', 3, 301);
insert into Livros (codAutor, Titulo, Editora, Edicao, NumeroPagina) values (17, 'Yu-Gi-Oh!', 'Katz', 2, 270);
insert into Livros (codAutor, Titulo, Editora, Edicao, NumeroPagina) values (16, 'The Secret Country: The First Australians Fight Back', 'Teklist', 4, 117);
insert into Livros (codAutor, Titulo, Editora, Edicao, NumeroPagina) values (1, 'Throw Momma from the Train', 'Dabshots', 4, 236);
insert into Livros (codAutor, Titulo, Editora, Edicao, NumeroPagina) values (18, 'Gabriel Over the White House', 'Ailane', 2, 185);
insert into Livros (codAutor, Titulo, Editora, Edicao, NumeroPagina) values (6, 'Universal Soldier: The Return', 'Vipe', 1, 114);
insert into Livros (codAutor, Titulo, Editora, Edicao, NumeroPagina) values (2, 'Big Fan', 'Flashset', 1, 268);
insert into Livros (codAutor, Titulo, Editora, Edicao, NumeroPagina) values (8, 'Cloud Atlas', 'Jetwire', 3, 151);
insert into Livros (codAutor, Titulo, Editora, Edicao, NumeroPagina) values (18, 'That''s The Way I Like It (a.k.a. Forever Fever)', 'Livetube', 2, 139);
insert into Livros (codAutor, Titulo, Editora, Edicao, NumeroPagina) values (10, 'Cold Fish (Tsumetai nettaigyo)', 'Thoughtblab', 3, 273);
insert into Livros (codAutor, Titulo, Editora, Edicao, NumeroPagina) values (6, 'World Before Her, The', 'Trilia', 2, 193);
insert into Livros (codAutor, Titulo, Editora, Edicao, NumeroPagina) values (11, 'Savage Nights (Nuits fauves, Les)', 'Leenti', 5, 28);
insert into Livros (codAutor, Titulo, Editora, Edicao, NumeroPagina) values (8, 'Hatchet II', 'Topicstorm', 3, 209);
insert into Livros (codAutor, Titulo, Editora, Edicao, NumeroPagina) values (19, 'Inherit the Wind', 'Brainsphere', 1, 181);
insert into Livros (codAutor, Titulo, Editora, Edicao, NumeroPagina) values (20, 'Danton', 'Devshare', 1, 52);
insert into Livros (codAutor, Titulo, Editora, Edicao, NumeroPagina) values (11, 'Angel in My Pocket', 'Rooxo', 5, 378);
insert into Livros (codAutor, Titulo, Editora, Edicao, NumeroPagina) values (14, 'Divorce, Le', 'Thoughtstorm', 3, 89);
insert into Livros (codAutor, Titulo, Editora, Edicao, NumeroPagina) values (17, 'All or Nothing', 'Shuffletag', 3, 147);
insert into Livros (codAutor, Titulo, Editora, Edicao, NumeroPagina) values (19, 'Flow', 'Omba', 3, 350);
insert into Livros (codAutor, Titulo, Editora, Edicao, NumeroPagina) values (4, 'Oak, The (Balanta)', 'Quimba', 1, 297);
insert into Livros (codAutor, Titulo, Editora, Edicao, NumeroPagina) values (17, 'Hava Nagila: The Movie', 'Wordtune', 1, 118);
insert into Livros (codAutor, Titulo, Editora, Edicao, NumeroPagina) values (8, 'Drug War (Du zhan)', 'Mydeo', 3, 345);
insert into Livros (codAutor, Titulo, Editora, Edicao, NumeroPagina) values (20, 'Black Nativity', 'Thoughtmix', 4, 164);
insert into Livros (codAutor, Titulo, Editora, Edicao, NumeroPagina) values (16, 'Sitting Pretty', 'Jayo', 4, 103);
insert into Livros (codAutor, Titulo, Editora, Edicao, NumeroPagina) values (18, 'Octopussy', 'Thoughtblab', 1, 132);
insert into Livros (codAutor, Titulo, Editora, Edicao, NumeroPagina) values (7, 'Paris Belongs to Us (Paris nous appartient)', 'Dabshots', 4, 351);
insert into Livros (codAutor, Titulo, Editora, Edicao, NumeroPagina) values (13, 'Bookies', 'Dabfeed', 3, 214);
insert into Livros (codAutor, Titulo, Editora, Edicao, NumeroPagina) values (3, 'Dark Passage', 'Abatz', 2, 242);
insert into Livros (codAutor, Titulo, Editora, Edicao, NumeroPagina) values (20, 'Lonely Are the Brave', 'Jetpulse', 2, 393);
insert into Livros (codAutor, Titulo, Editora, Edicao, NumeroPagina) values (12, 'Revolution', 'Livetube', 5, 136);
insert into Livros (codAutor, Titulo, Editora, Edicao, NumeroPagina) values (14, 'Hero', 'Bubblebox', 3, 262);
insert into Livros (codAutor, Titulo, Editora, Edicao, NumeroPagina) values (7, 'Comrades', 'Jabberstorm', 2, 67);
insert into Livros (codAutor, Titulo, Editora, Edicao, NumeroPagina) values (16, 'Great Waltz, The', 'Youspan', 4, 128);
insert into Livros (codAutor, Titulo, Editora, Edicao, NumeroPagina) values (4, 'Mountain, The', 'Chatterbridge', 2, 54);
insert into Livros (codAutor, Titulo, Editora, Edicao, NumeroPagina) values (12, 'Brenda Starr', 'Tekfly', 5, 172);
